version: "3.5"

services:

  nginx-proxy:
    image: "jwilder/nginx-proxy"
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - "proxy"

  nginx-proxy-letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:

networks:
  proxy:
    name: "proxy"
